# Dockerfile for ARMOURY-Docker
# Cross compiler stuff
# by Saumil Shah

FROM debian:stable-slim

# Install packages
RUN apt update && \
    apt upgrade --yes && \
    apt install sudo \
                curl \
                wget \
                vim \
                locales \
                procps \
                build-essential \
                ncurses-dev \
                elfutils \
                --yes

WORKDIR /opt

RUN curl -L https://github.com/therealsaumil/emux-buildroot-toolchains/raw/master/arm-unknown-linux.tar.xz | tar -Jxv
RUN curl -L https://github.com/therealsaumil/emux-buildroot-toolchains/raw/master/mips-unknown-linux.tar.xz | tar -Jxv
RUN curl -L https://github.com/therealsaumil/emux-buildroot-toolchains/raw/master/mipsel-unknown-linux.tar.xz | tar -Jxv
RUN curl -L https://github.com/therealsaumil/emux-buildroot-toolchains/raw/master/aarch64-buildroot-linux-uclibc.tar.xz | tar -Jxv

# Create an xdev user for all userland work
RUN adduser --disabled-password --gecos "" xdev
RUN echo 'xdev ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers

# Set xdev's shell to bash
RUN sed -i 's!/bin/ash!/bin/bash!g' /etc/passwd

# Set up the home directory of xdev user
WORKDIR /home/xdev

# Add bashrc, ssh configs, etc
COPY --chown=xdev files/home/xdev/bashrc .bashrc
COPY --chown=xdev files/home/xdev/profile .profile
COPY --chown=xdev files/home/xdev/dircolors .dircolors

COPY --chown=root files/home/xdev/bashrc /root/.bashrc
COPY --chown=root files/home/xdev/profile /root/.profile
COPY --chown=root files/home/xdev/dircolors /root/.dircolors

# Set up the docker entrypoint script
COPY ./docker-entrypoint.sh /usr/local/bin

USER xdev

ENV TERM xterm-256color
ENV LANG C.UTF-8
ENV CHARSET UTF-8
ENV LC_COLLATE C

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["/bin/bash"]
