#!/bin/bash

OWNERNAME="therealsaumil"
IMAGENAME="armoury"
TAGNAME="07-2022"

docker run \
	-it \
	--rm \
	--name armoury-docker \
	-v "$(pwd)/workspace:/home/xdev/workspace" \
	$OWNERNAME/$IMAGENAME:$TAGNAME $*
