#!/bin/bash

OWNERNAME="therealsaumil"
IMAGENAME="armoury"
TAGNAME="07-2022"

docker run \
	-it \
	--rm \
	--name armoury-docker \
	--mount "type=bind,src=$(pwd)/workspace,dst=/home/xdev/workspace" \
	$OWNERNAME/$IMAGENAME:$TAGNAME $*
